---

- name: Make mountpoint
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: true

- name: Mount volume from UUID
  ansible.posix.mount:
    path: "{{ mountpoint }}"
    src: "UUID={{ uuid }}"
    state: mounted
    fstype: "{{ fstype }}"
  become: true