---
- debug:
    msg: "{{ mountpoint }}"

- name: Make mountpoint
  ansible.builtin.file:
    path: "{{ mountpoint }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: true
  when: false